### ISSUE TITLE
/core-model-1-4:control-construct/uuid is missing

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/TypeApprovalRegister#1]
In /core-model-1-4:control-construct :: responses
core-model-1-4:control-construct should be complemented with 
```
required:
  - uuid
```
and
```
properties:
  uuid:
    type: string
```

**Comment by PrathibaJee** [comment]
Also , please consider the following change , 
- [ ]  CONFIGfile needs to be added with the control-construct::uuid

**Comment by openBackhaul** [comment]
No individual /core-model-1-4:control-construct.
/core-model-1-4:control-construct at ApplicationPattern contains the required uuid attribute.
CONFIGfile has been complemented, too.
=> Completed.
