### ISSUE TITLE
Update Dummy operation-name generating functions

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#131]
Currently, few testcases has function defined for generating the next version of given operation-name for testing the configurable parameter /operation-client-interface-configuration/operation-name. This needs to be updated to function that generates a random string, since in future operation-name need not have its version number in it.
Here, the function named GenerateDummyOperationName() to be updated to function GenerateRandomString()
Mainly, this is present in following services

 Update LTP notified? :: operation-name update notified to ALT?
- [ ] /v1/redirect-info-about-approval-status-changes

**Comment by vanithavalluripalli9** [comment]
Fixed as part of pull request #191
