### ISSUE TITLE
Update testcase logic in Response body completeness : test against load file

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#136]
While checking Response body completeness, along with testing the response-body against schema, we also test the response-body values against initial load-file. Expectation is that the data is present in initial state still during testing phase.
- [ ] /v1/list-applications
- [ ] /v1/list-approved-applications-in-generic-representation

**Comment by vanithavalluripalli9** [comment]
As the data is now stored in Application data file we can't check it against initial load file.
