### ISSUE TITLE
operation-name attributes to be checked for Attribute correctness

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#140]
In v2.0.0, all operations are added with a constraint to have minLength: 6. This need to be tested for correctness in Acceptance section under

Service Layer :: Attribute correctness
- [x] /v1/redirect-info-about-approval-status-changes
  - subscriber-operation

**Comment by vanithavalluripalli9** [comment]
Fixed as part of issue #191
