### ISSUE TITLE
Add testcase for "Attribute configured?" check of protocol attribute

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#143]
protocol is an attribute added to multiple services. This attribute is an enumeration of two values like "HTTP" and "HTTPS". To check if server is accepting and configuring the input values given from user, testcase to be added to applicable services under "Acceptance" :: "Attribute configured?" section.
Services required for changes are
- [x] /v1/bequeath-your-data-and-die
- [x]  /v1/redirect-info-about-approval-status-changes

**Comment by vanithavalluripalli9** [comment]
Fixed as part of pull #191
