### ISSUE TITLE
getOperationClientDetailedLoggingIsOn and putOperationClientDetailedLoggingIsOn uuid pattern needs an update

### ISSUE THREAD

**Issue by ManasaBM1** [openBackhaul/TypeApprovalRegister#205]
Observation:
In the getOperationClientDetailedLoggingIsOn and putOperationClientDetailedLoggingIsOn uuid pattern shall be  ^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-**_bs_**-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$. (_With api-segment as "bs" instead of "bm")_

But in [TAR.yaml](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister.yaml) file, it is present as  "^([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-op-c-bm-([a-z]{2,6})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{1,2})-([0-9]{3})$". 

Solution: the api-segment in uuid pattern of getOperationClientDetailedLoggingIsOn and putOperationClientDetailedLoggingIsOn shall be updated to "bs" instead of "bm"

**Comment by openBackhaul** [comment]
Changed as proposed.
