### ISSUE TITLE
PromptForBequeathingDataCausesTransferOfListOfAlreadyGrantedTypeApprovals :: name could be updated

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#224]
PromptForBequeathingDataCausesTransferOfListOfAlreadyGrantedTypeApprovals is a callback of service /v1/bequeath-your-data-and-die. 
As name suggests the callback shall only transfer "approved" application to future-application. 

But few applications waiting for approval (in "REGISTERED" state ) could be lost in old-application. 

Proposal: 
The name of this callback could be updated in a way that it is understandable that all available applications in application-data file could be transferred. Example: PromptForBequeathingDataCausesTransferOfListOfApplications

**Comment by openBackhaul** [comment]
**Required change to the OAS:**
The _PromptForBequeathingDataCausesTransferOfListOfAlreadyGrantedTypeApprovals_ callback's name shall be changed towards 
_PromptForBequeathingDataCausesTransferOfListOfApplications_.

**Comment by openBackhaul** [comment]
Changed as decided.
