### ISSUE TITLE
/v1/list-approved-applications-in-generic-representation service is getting stuck 

### ISSUE THREAD

**Issue by vanithavalluripalli9** [openBackhaul/TypeApprovalRegister#232]
**Problem Description:**

When we execute /v1/list-approved-applications-in-generic-representation is getting stuck with below mentioned error 

undefined
(node:15324) Warning: Accessing non-existent property 'getProfileListAsync' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)

**Comment by DanaSunal** [comment]
Pull request was created. I believe that the list consequent-action-list will stay empty for this response, is that correct?

**Comment by PrathibaJee** [comment]
@DanaSunal , yes you are right. There will be no consequent action for this request  as there is no action-profile defined for this request "/v1/list-approved-applications-in-generic-representation" in the configuration file.
