### ISSUE TITLE
Testexecution PostTermination mismatch in the initial and final configuration file

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/TypeApprovalRegister#265]
**Assertion failure details**
In TAR SoftwareUpgrade , following are the assertions that are failed because of this problem, 

1. Provides expected properties in configuration class for 'tar-2-0-1-tcp-c-or-1-0-0-000'
2. Provides expected properties in configuration class for 'tar-2-0-1-http-c-cc-1-0-0-000'

Reason  :
In the test execution, the expectation is , the initial configuration file should match the final configuration.
But there is a mismatch. This mismatch are consequences of the failures of other assertions. Once the other assertion failures will be resolved , this shall also be cleared.

**Comment by IswaryaaS** [comment]
Closing this issue as the test-suite is not updated for version 2.1.1
