### ISSUE TITLE
/v1/bequeath-your-data-and-die not transferring all the regarded application

### ISSUE THREAD

**Issue by sunil-kumar-meena** [openBackhaul/TypeApprovalRegister#266]
To transfer the regarded application during /v1/bequeath-your-data-and-die , as per the load file , oldRelease have to transfer 7 applications to newRelease. 
But , as per the records in EATL , only 6 such records are there.

>Priority:Medium;
>AffectedFlow:Software Upgrade/TAR:/v1/bequeath-your-data-and-die;

**Comment by PrathibaJee** [comment]
**Assertion failure details**
1. The forwarding for 'bequeathYourDataAndDie' is successful. 
expected false to be true
2. As expected, 8 requests could be found for /v1/document-approval-status successful 
expected 7 to equal 8
3. As expected, the forwarding 'PromptForBequeathingDataCausesRequestForBroadcastingInfoAboutServerReplacement' is not successful 
expected true to equal false
