### ISSUE TITLE
REDIRECT-INFO-ABOUT-APPROVAL-STATUS-CHANGES - testsuite should allow new tcp client to be created

### ISSUE THREAD

**Issue by DanaSunal** [openBackhaul/TypeApprovalRegister#285]
SERVICELAYER / INDIVIDUALPART / /V1/REDIRECT-INFO-ABOUT-APPROVAL-STATUS-CHANGES / ACCEPTANCE / ATTRIBUTE CONFIGURED? / SUBSCRIBER-PROTOCOL UPDATED? - 5 REQUESTS IN THE FOLDER

This operation (always) changes attributes of registry office. The test proposes protocol of HTTPS, which is for RO not configured. Per openBackhaul/ApplicationPattern#858 both protocols are supported for RO,therefore the testsuite should not expect existing tcp client to be changed, but a new tcp client to be created.

This also impacts:
- SERVICELAYER / INDIVIDUALPART / /V1/REDIRECT-INFO-ABOUT-APPROVAL-STATUS-CHANGES / ACCEPTANCE / UPDATE LTP NOTIFIED? / SUBSCRIBER-PROTOCOL UPDATE - 9 REQUESTS IN THE FOLDER
- PostTermination - 2 Requests in the folder

**Comment by IswaryaaS** [comment]
As per specification of subscriber-protocol of /v1/redirect-info-about-approval-status-changes (_update [/core-model-1-4:control-construct/logical-termination-point=tar-2-0-2-tcp-c-ro-2-0-2-000/layer-protocol=0/tcp-client-interface-1-0:tcp-client-interface-pac/tcp-client-interface-configuration/remote-protocol]_'), the tcp-client instance _shall be expected only to be updated_ and a new instance is not expected to be created. 

Closing the issue assuming no change is required in test-suite. 
@DanaSunal , kindly reopen the issue if my understanding is conflicting
