### ISSUE TITLE
Proposal To include the x-correlator of the API /v1/document-embedding-status to the LOAD file

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/TypeApprovalRegister#298]
After an application is approved by a human , TAR will inform the approval status to RO via /v1/regard-updated-approval-status(TAR will generate an **x-correlator(lets say : ABCDEF**) while initiating this request).
Further , RO will initiate a sequence of procedure to embed the approved application.(RO will use the same **x-correlator: ABCDEF** while initiating each request of the sequential procedure).
After completing the sequential procedure, RO will inform the result to TAR via the request /v1/document-embedding-status(RO will use the same **x-correlator: ABCDEF** while initiating this request aswell).

After receiving the request /v1/document-embedding-status , TAR will save the following information to the LOAD file  ,
1. embedding-status, 
2. reason-of-failure

**Proposal :**
Along with this , shall we also store the x-correlator of the received request(/v1/document-embedding-status) to the LOAD file.
This stored x-correlator will be useful to troubleshoot in case of any problem.
If we are fine with this proposal , we shall also show this associated x-correlator as a response attribute of the APIs /v1/list-applications , /v1/list-applications-in-gui.

**Comment by openBackhaul** [comment]
OAS:
- x-correlator parameter at /v1/document-embedding-status path changed to update LOADfile
```diff
  /v1/document-embedding-status:
    parameters:
      - $ref: '#/components/parameters/user'
      - $ref: '#/components/parameters/originator'
-      - $ref: '#/components/parameters/x-correlator'
+      - name: x-correlator
+        in: header
+        required: true
+        schema:
+          type: string
+          pattern: '^[0-9A-Fa-f]{8}(?:-[0-9A-Fa-f]{4}){3}-[0-9A-Fa-f]{12}$'
+          description: 'Empty string accepted from external applications.'
+          example: '550e8400-e29b-11d4-a716-446655440000'
+        description: >
+          'UUID for the service execution flow that allows to correlate requests and responses
+          update in LOADfile'
      - $ref: '#/components/parameters/trace-indicator'
      - $ref: '#/components/parameters/customer-journey'
```
- x-correlator attribute added to ResponseBody of /v1/list-applications
- x-correlator attribute added to ResponseBody of /v1/list-applications-in-gui
- x-correlator attribute added to ResponseBody of GuiRequestForVisualizingListOfApplicationsCauses.RetrievingListOfApplications callback at /v1/list-applications-in-gui
- x-correlator added to GUI
