### ISSUE TITLE
Type Issues found in spec files

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#301]
- [x] In [forwardings.yaml](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bconfig.json), in INPUT fc-port of forwarding-construct _ServiceRequestCausesLoggingRequest_, we shall need to add the following services.
  - tar-2-1-0-op-s-bm-013 - /v1/dispose-remainders-of-deregistered-application
  - tar-2-1-0-op-s-bm-014 - /v1/inform-about-preceding-release
  - tar-2-1-0-op-s-bm-015 - /v1/update-client-of-subsequent-release
 
- [x] Since, /v1/update-client-of-subsequent-release could update ltp instances in load file, this shall be eligible for sending a LTPUpdate request to ALT. In forwarding-construct _ServiceRequestCausesLtpUpdateRequest_, _/v1/update-client-of-subsequent-release (tar-2-1-0-op-s-bm-015)_ is to be added into INPUT fc-port list.
 This change is required in both [forwardings.yaml](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bforwardings.yaml) and [config.json](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bconfig.json) files.

- [x] In [forwardings.yaml](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bforwardings.yaml), the client-name of consequent-requests of forwarding-constructs  - _GuiRequestForVisualizingListOfApplicationsCauses.Authentication_ and _GuiRequestForDocumentingAnApprovalStatusChangeCauses.Authentication_ shall be updated as _/v1/approve-oam-request_. 
        - This is because  AA://v1/approve-basic-auth-request is introduced in  AccessAdministration v2.1.0. But we are referring to AdministratorAdministration v2.0.1 in config file. 

- [x] In [config.json](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bconfig.json) file, _release-list/local-id_ of release-number 2.1.0 shall be "_2_" for http-server instance tar-2-1-0-http-s-000

- [x]  In [config.json](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bconfig.json) file, value of remote-port of tar-2-1-0-tcp-c-nr-2-1-0-000 shall be _3025_

- [x] In [config.json](https://github.com/openBackhaul/TypeApprovalRegister/blob/develop/spec/TypeApprovalRegister%2Bconfig.json) file, release-number of Registryoffice http-client instance tar-2-1-0-http-c-ro-2-1-0-000 shall be _2.1.0_

**Comment by openBackhaul** [comment]
Changed as proposed.
