### ISSUE TITLE
To remove the uuid tar-2-1-0-op-s-bs-000 from the client-ltp list of tar-2-1-0-http-s-000

### ISSUE THREAD

**Issue by PrathibaJee** [openBackhaul/TypeApprovalRegister#316]
In the [configuration file](https://github.com/openBackhaul/TypeApprovalRegister/blob/v2.1.1_spec/spec/TypeApprovalRegister%2Bconfig.json) 
, the The uuid tar-2-1-0-op-s-bs-000 is repeated twice in the client-ltp list of tar-2-1-0-http-s-000.
So , one entry should be removed.

**Comment by openBackhaul** [comment]
Corrected as proposed.
