### ISSUE TITLE
To remove schema description for the request-header x-correlator for /v1/document-embedding-status

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#373]
In OAS, we have an IndividualService /v1/document-embedding-status. In this service, we have a request-header parameter "x-correlator" the specification of which is as follows:
![image](https://github.com/user-attachments/assets/7adba890-29ed-498c-95f9-e4e9cea6fc3d)

Problem:
- As per the description provided,  `Empty string accepted from external applications.` which is contradicting with the `required: true` constraint provided. 
- Also, this description explains that the incoming request can have x-correlator provided as an empty string. As per given pattern, which does not allow an empty string. 

Proposal:
-  We shall remove the line `description: 'Empty string accepted from external applications.' ` from specification.

**Comment by openBackhaul** [comment]
Corrected as proposed.
