### ISSUE TITLE
Include description in service /v1/approve-application-in-gui for updating incoming x-correlator to the LOADfile

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#374]
As per current workflow, the x-correlator is written to the LOADfile during /v1/document-embdding-status.
![image](https://github.com/user-attachments/assets/8935c989-f708-4d85-a50f-efddae260c5c). 

problem:
- /v1/document-embedding-status is received to TypeApprovalRegister only when RegistryOffice completes the embedding process and sends a callback. 
- In this case, TAR will not be aware of the x-correlator until RO completes it's cycle. 
- In middle of this process, a user(say an admin) could not follow-up the embedding process. 
- If we could write the x-correlator into LOADfile once /v1/approve-application-in-gui is received, follow-up on the embedding process would become easier.

Proposal: 
A description shall be added to the service /v1/approve-application-in-gui like **_"Update in LOADfile"_** under request-header parameter x-correlator. 

Kindly let us know your views.

**Comment by openBackhaul** [comment]
Moved writing the x-correlator into the LOADfile from /v1/document-embedding-status to /v1/document-approval-status (as discussed during call).
