### ISSUE TITLE
Update TAR with replacing AdministratorAdministration with AccessAdministration in application-data.json

### ISSUE THREAD

**Issue by sunil-kumar-meena** [openBackhaul/TypeApprovalRegister#395]
1. Update TAR with replacing AdministratorAdministration with AccessAdministration in application-data.json
2. remove ./server dir from root

**Comment by IswaryaaS** [comment]
the solution is not applied to BasicServices.js/embedYourself . 

@sunil-kumar-meena , please update the code and raise a PR for the same. Thanks

**Comment by sunil-kumar-meena** [comment]
issue has been covered under https://github.com/openBackhaul/TypeApprovalRegister/pull/396
