### ISSUE TITLE
Server : /v1/document-approval-status : not creating a new application-profile instance

### ISSUE THREAD

**Issue by IswaryaaS** [openBackhaul/TypeApprovalRegister#49]
As per expectation, on triggering /v1/document-approval-status of a new application should create a new instance in application-profile list even if it was not created as a part of /v1/regard-application. 
The server needs to additionally support this expectation of creating new profile instance for a completely new application through /v1/document-approval-status.

**Comment by PrathibaJee** [comment]
Issue fixed as in the pull request https://github.com/openBackhaul/TypeApprovalRegister/pull/50 . The /v1/document-approval-status creates a profile instance incase if the application is not even registered using /v1/regard-application.
