### ISSUE TITLE
Update UUIDs of Services

### ISSUE THREAD

**Issue by openBackhaul** [openBackhaul/TypeApprovalRegister#69]
Process for updating the UUIDs of Services

- [x] Thorsten to check categories of OperationServers and OperationClients in ServiceList
- [x] Iswaryaa to review categories of OperationServers and OperationClients in ServiceList
- [x] Katharina to add new UUIDs based on category of operation (but not old UUID) in ServiceList
- [x] Iswaryaa to review new UUIDs in ServiceList
- [x] Katharina to CTRL+h for old UUIDs and replace them by new UUIDs in ForwardingList, CONFIGfile and OAS.
- [x] Katharina to step through ForwardingList, CONFIGfile and OAS and compare every UUID against new one in ServiceList
- [x] Iswaryaa to review new UUIDs in ForwardingList, CONFIGfile and OAS

If no errors found
- [x] Iswaryaa to delete old UUIDs in ServiceList
- [x] Iswaryaa to merge the feature branch into develop
- [x] Iswaryaa to close this issue and delete the feature branch on GitHub

**Comment by kmohr-soprasteria** [comment]
Mappings done according to following mapping table:
[mappingtable_TAR.txt](https://github.com/openBackhaul/TypeApprovalRegister/files/10030845/mappingtable_TAR.txt)

**Comment by kmohr-soprasteria** [comment]
After merge with develop oas already contains tar-2-0-0 uuids, whereas serviceList still has tar-1-0-0 ids.
The following service uuids, which needed mapping were found:
![mapping](https://user-images.githubusercontent.com/57349523/203300771-bb17e0a5-0796-4925-a827-e0364aebc68a.png)
